# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

sensor:
  - platform: foxess
    username: !secret foxess-user
    password: !secret foxess-pass
    deviceID: !secret foxess-DID

  - platform: seventeentrack
    username: !secret seventeentrack-user
    password: !secret seventeentrack-pass

waste_collection_schedule:
  sources:
    - name: cornwall_gov_uk
      args:
        postcode: !secret postcode
        housenumberorname: !secret housenumber
        uprn: !secret uprn

shell_command:
  pushupdates_to_github: /bin/bash pushupdates.sh

logger:
  default: warning
  logs:
    custom_components.foxess: debug