external_components:
  - source:
      type: local
      path: ../esphome/components
    components: [ udp_stream, version ]
    

text_sensor:
  - platform: version
    name: ${node_name}-firmware
    hide_timestamp: true
