esphome:
  name: 0625-coreboard
  friendly_name: 0625-Coreboard
  platformio_options:
    board_build.flash_mode: dio
    board_build.extra_flags:
      - "-DARDUINO_USB_CDC_ON_BOOT=0"  # Override, defaults to '-DARDUINO_USB_CDC_ON_BOOT=1'
      - "-DARDUINO_USB_MODE=0"

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino