# Basic Config
substitutions:
  lowercase_name: esp32-korvo-01
  friendly_name: esp32-korvo
  static_ip: 10.10.1.80

esphome:
  name: ${lowercase_name}

esp32:
  board: esp-wrover-kit
  framework:
    type: arduino
    version: recommended

captive_portal:

external_components:
  - source: github://rpatel3001/esphome@es8311
    components: [ es8311 ]

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_pass

ota:
  password: !secret ota_pass

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  manual_ip:
    # Set this to the IP of the ESP
    static_ip: ${static_ip}
    # Set this to the IP address of the router. Often ends with .1
    gateway: !secret wifigateway
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: !secret wifisubnet

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${lowercase_name}
    password: !secret ap-pass

i2c:
  sda: GPIO19 #GPIO1
  scl: GPIO32 #GPIO2
  # scan: true
  # frequency: 400kHz

es8311:
  address: 0x18

i2s_audio:
  i2s_lrclk_pin: GPIO22
  i2s_bclk_pin: GPIO25
  i2s_mclk_pin: GPIO0

media_player:
  - platform: i2s_audio
    name: "esp32-korvo"
    dac_type: external
    i2s_dout_pin: GPIO13
    mode: mono