# Basic Config
substitutions:
  lowercase_name: porch-pir
  friendly_name: Porch PIR
  static_ip: 10.10.1.80
  
esphome:
  name: ${lowercase_name}
  friendly_name: ${friendly_name}

esp8266:
  board: esp01_1m

# Make sure logging is not using the serial port
# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_pass

ota:
  password: !secret ota_pass

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${lowercase_name}
    password: !secret ap-pass

captive_portal:

uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 9600

# Register the Tuya MCU connection
tuya: